import streamlit as st
from dotenv import load_dotenv
import parrot_toolkit.devotional as dtk
from datetime import datetime as dt
import pytz
et = pytz.timezone('US/Eastern')

load_dotenv()

st.set_page_config(
    page_title="Devotional Parrot", 
    page_icon="📜",
    layout="wide",
    menu_items={
        'Get help': 'https://svrbc.org/',
        'About': "v2.4\n\nCreated by: [Jesús Mancilla](mailto:jesus@jgmancilla.com)\n\nFrom [SVRBC](https://svrbc.org/)\n\n"
    }
)

class devotional_parrot:
    def __init__(self):
        self.now = dt.now(et)
        self.devotional_type = "evening" if self.now.hour >= 17 or self.now.hour < 5 else "morning"
        self.id = self.now.strftime("%Y_%m_%d")
        self.id += f"_{self.devotional_type}_devotional"
        if "devotional" not in st.session_state:
            devotional = dtk.check_if_devotional_exists(self.id)
            if devotional is not None:
                st.session_state["devotional"] = devotional
            else:
                with st.spinner("Generating..."):
                    dtk.generate_devotional()
                    st.session_state["devotional"] = dtk.check_if_devotional_exists(self.id)

    def main(self):
        if "page" not in st.session_state:
            st.session_state["page"] = "Devotional"
        if st.session_state.page != "Devotional":
            st.session_state["page"] = "Devotional"
        
        st.header(f"Devotional for {self.now.strftime('%A, %B %d, %Y')}")
        st.subheader(st.session_state.devotional.title)
        st.write(f"{self.devotional_type.capitalize()} devotional")
        st.divider()
        st.write(dtk.get_text(st.session_state.devotional.bible_verse))
        st.divider()
        st.write(st.session_state.devotional.devotional_text)
        st.divider()
        st.write("This devotional was generated by AI. If you have any questions or comments, please email [Jesús Mancilla](mailto:jgmancilla@svrbc.org)")
        with st.expander(f"📰 **Additional information**"):
            st.write("News articles used to generate this devotional:")
            st.write(" - " + st.session_state.devotional.news_articles)

if __name__ == "__main__":
    obj = devotional_parrot()
    obj.main()