import streamlit as st
from dotenv import load_dotenv
import parrot_ai.devotional as dtk
from datetime import datetime as dt
import pytz
et = pytz.timezone('US/Eastern')

load_dotenv()

now_ = dt.now(et)
devotional_type = "evening" if now_.hour >= 17 or now_.hour < 5 else "morning"
id_ = now_.strftime("%Y_%m_%d")
id_ += f"_{devotional_type}_devotional"

if "devotional" not in st.session_state:
    devotional = dtk.check_if_devotional_exists(id_)
    if devotional is not None:
        st.session_state["devotional"] = devotional
    else:
        with st.spinner("Generating..."):
            dtk.generate_devotional()
            st.session_state["devotional"] = dtk.check_if_devotional_exists(id_)

if "page" not in st.session_state:
    st.session_state["page"] = "Devotional"
if st.session_state.page != "Devotional":
    st.session_state["page"] = "Devotional"

st.header(f"Devotional for {now_.strftime('%A, %B %d, %Y')}")
st.subheader(st.session_state.devotional.title)
st.write(f"{devotional_type.capitalize()} devotional")
st.divider()
st.write(dtk.get_text(st.session_state.devotional.bible_verse))
st.divider()
st.write(st.session_state.devotional.devotional_text)
st.divider()
st.write("This devotional was generated by AI. If you have any questions or comments, please email [Jesús Mancilla](mailto:jgmancilla@svrbc.org)")
with st.expander(f"📰 **Additional information**"):
    st.write("News articles used to generate this devotional:")
    st.write(" - " + st.session_state.devotional.news_articles)